name: Build and publish it on GitHub releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout sources
        uses: actions/checkout@v2
      - name: Step 2 - Download a file from another repository
        # @todo Download and unzip the whole package
        run: |
          wget https://netresearch.github.io/ckeditor-cowriter/plugin.js -O Resources/Public/JavaScript/Plugins/ckeditor-cowriter/plugin.js
      - name: Step 3 - ZIP the whole package
        run: |
          zip -r t3-cowriter-${{ github.ref_name }}.zip ./
      - name: Step 4 - Upload the package artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./t3-cowriter-${{ github.ref_name }}.zip
          if-no-files-found: error
          retention-days: 12

  release:
    name: release – ${{ github.ref_name }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Step 1 - Checkout sources
        uses: actions/checkout@v2
      - name: Step 2 - Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: t3-cowriter-${{ github.ref_name }}.zip
          path: package
      - name: Step 3 - Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            #### Changes in this Release

            - ${{ github.event.head_commit.message }}

            #### Download

            [![Badge Package Download](https://img.shields.io/badge/DE-Introduction-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/t3-cowriter-${{ github.ref_name }}.zip)
          draft: false
          prerelease: false

      - name: Step 4 -  Upload to release page
        id: upload-release-asset-package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/t3-cowriter-${{ github.ref_name }}.zip
          asset_name: t3-cowriter-${{ github.ref_name }}.zip
          asset_content_type: application/zipped
